version: '3.9'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=computer_company
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}